### ISSUE TITLE
Apple Pay Payment Method appear on Android device

### ISSUE THREAD

**Issue by Thibault4** [Adyen/adyen-flutter#119]
**Describe the bug**
I'm encountering an unexpected behavior in my Flutter application where the Apple Pay payment method is appearing on Android devices. Despite the fact that the plugin I'm using is in beta, I wouldn't expect Apple Pay to be available on Android devices. This inconsistency is causing confusion for users and is not the intended behavior.

**To Reproduce**
1. Go to MyPage
2. Click on Icon.card
4. See Apple Pay method

**Expected behavior**
`
import 'package:adyen_checkout/adyen_checkout.dart';
import 'package:flutter/material.dart';
import 'package:dio/dio.dart';

class MyPage extends StatelessWidget {
  final String apiUrl = 'http://192.168.1.35:3000/api'; // Votre URL d'API Adyen

  Future<Map<String, dynamic>> getSessionData() async {
    try {
      // Effectuez une requête HTTP GET à votre endpoint /sessions pour obtenir les données de session
      Response response = await Dio().post('$apiUrl/sessions');
      print('Return data ' + response.data.toString());
      return response.data;
    } catch (error) {
      throw Exception('Failed to load session data ' + error.toString());
    }
  }

  void startDropIn(BuildContext context) async {
    try {
      // Obtenez les données de session
      Map<String, dynamic> sessionData = await getSessionData();

      // Créez la configuration DropIn
      DropInConfiguration dropInConfiguration = DropInConfiguration(
        environment: Environment
            .test, // Changez pour 'live' lorsque vous êtes prêt à accepter de vrais paiements
        clientKey: '*******',
        countryCode: 'fr',
        shopperLocale: 'fr',
        amount: Amount(value: 1000, currency: 'EUR'),
      );

      final SessionCheckout sessionCheckout =
          await AdyenCheckout.session.create(
        sessionId: sessionData['id'],
        sessionData: sessionData['sessionData'],
        configuration: dropInConfiguration,
      );

      final PaymentResult paymentResult =
          await AdyenCheckout.session.startDropIn(
        dropInConfiguration: dropInConfiguration,
        checkout: sessionCheckout,
      );

      if (paymentResult is PaymentError) {
        print('Error ' + paymentResult.reason!);
      } else {
        print(paymentResult);
      }
    } catch (error) {
      // Gérer les erreurs
      print('Error starting Drop-in: $error');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Adyen Payment Demo'),
      ),
      body: Center(
        child: IconButton(
          onPressed: () {
            startDropIn(context);
          },
          icon: const Icon(Icons.payment),
        ),
      ),
    );
  }
}
`

**Screenshots**
![Screenshot_1708161059](https://github.com/Adyen/adyen-flutter/assets/60462742/32ae6120-d82d-4994-8c2c-e1cd7499593b)
![Screenshot_1708161107](https://github.com/Adyen/adyen-flutter/assets/60462742/c2e4189b-7523-4159-8a2e-d5ebbf258f22)

**Smartphone (please complete the following information):**
 - Device: Android 3 XL API 34
 - OS: Android v14
 - Browser 
 - Version

**Additional context**
On iOS I don't have google pay that is ok

**Comment by Robert-SD** [comment]
Hello Thibault, 

Thanks for providing the bug description. The expected behavior is correct and Apple Pay is not supported on Android devices.

In order to filter out non supported payment methods, it is necessary to provide the [“channel” parameter](https://docs.adyen.com/api-explorer/Checkout/71/post/sessions#request-channel) in the POST /sessions request body in your backend implementation. The value needs to be set to either “iOS” or “Android” depending on the platform where the payment transaction takes place.
 
Could you add this parameter and test it again? Apple Pay should not appear anymore on the Android device.  

Please let me know if you need further assistance.

**Comment by Robert-SD** [comment]
Hello @Thibault4, we closed the issue. Feel free to reach out in case you need any further assistance.

**Comment by Robert-SD** [comment]
Hey @shownChowbus,
For an integration using sessions, it's necessary to include the [channel](https://docs.adyen.com/api-explorer/Checkout/70/post/sessions#request-channel) field in the /sessions endpoint call on your backend. Would that be a feasible option? 

With the advanced flow, local filtering of the payment methods list is possible. However, in sessions, this list is embedded within the session data object, making client-side modifications unfeasible. Therefore, client-side filtering is not supported for sessions.
