### ISSUE TITLE
Is there any way I can fetch encrypted CVV for recurring payments? 

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [Adyen/adyen-flutter#145]
I am integrating Adyen in my flutter app. My app used tokenisation for next payments. I have fetched stored payment methods but to complete my payments I want encrypted CVV. Is there any way I can receive existing encrypted CVV?

**Comment by Robert-SD** [comment]
Hi @ChandraPrakashJangid, 

I would like to help you setting up the payment flow with tokenized payments. Could you explain your goal in more detail and describe which integration you use (Drop-in or Components with session or advanced checkout)? That would be very helpful. 
For example, you can use Drop-in with the sessions flow and configure a `StoredPaymentMethodConfiguration` to directly show the stored payment method to your customers so they can just proceed with authorizing the transaction.

**Comment by ChandraPrakashJangid** [comment]
@Robert-SD I am implementing the credit card payment with tokenisation. Here are the steps I want to follow:

1. User has to add credit card first. I have completed this step. 
2. Now User can set his primary payment method if User has multiple cards. 
3. User can pay by just tapping on pay button without showing any other screen in background. User has the order performa screen as soon as User taps on the pay button amount paid from his primary payment method. 
4. I want to do this 3rd step using tokenisation.

**Comment by camil-adyen** [comment]
Hi @ChandraPrakashJangid, if the shopper is present we strongly advice you to ask them to submit the CVV again. Recurring payments without CVV have a higher refusal rate. Also, the encrypted CVV that is generated when the shopper stores their details in the first step is only valid for a limited amount of time. We do not store the CVV in the token. 

If you do want to proceed with a recurring payment without asking for the CVV, you can contact our support team. 

More information on tokenization can be found on our [docs page](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens/#pay-one-off).

**Comment by camil-adyen** [comment]
Hi @ChandraPrakashJangid, thank you for clarifying. 

Currently, we only support encrypting the CVV through our card component ([advanced flow](https://github.com/Adyen/adyen-flutter?tab=readme-ov-file#card-component-with-advanced-flow) and [sessions flow](https://github.com/Adyen/adyen-flutter?tab=readme-ov-file#card-component-with-sessions-flow)). The implementation of a CSE library to support encryption via your own UI is on our backlog for Q2 '24. 

I hope this answers your question!

Kind regards,
Camil

**Comment by ChandraPrakashJangid** [comment]
@camil-adyen As per your answer for now we can't do token payment.

**Comment by Robert-SD** [comment]
Hey @ChandraPrakashJangid 

We merged the branch for adding client side encryption (CSE). With the next release, the feature will become available. 
Because of that we will close your issue for now. But feel free to open it again or reach out in case you have additional questions. 

Regards Robert

**Comment by MickaelTitecaTAO** [comment]
Hi @camil-adyen @Robert-SD 

@ChandraPrakashJangid asks for a solution to encrypt CVV for a stored card from its own UI. 
Your CSE works for new cards only.
Is it planned to have CSE for CVV for a stored card without using Adyen Card component ?
