### ISSUE TITLE
'PaymentCancelledByUser' is not a subtype of type 'PaymentSessionFinished'

### ISSUE THREAD

**Issue by matmicro** [Adyen/adyen-flutter#199]
**Describe the bug**
How to handle Cancel by user, by using button back on the Adyen widget ?
I am currently facing exception "type 'PaymentCancelledByUser' is not a subtype of type 'PaymentSessionFinished' in type cast".
I would like to know how to handle it correctly.

**To Reproduce**
1. Open the dropin as if you want to pay
2. Click on back button to close the widget
Exception is raised:
"type 'PaymentCancelledByUser' is not a subtype of type 'PaymentSessionFinished' in type cast"

**Current Code**
      
```
      import 'package:adyen_checkout/adyen_checkout.dart' as adyen;

      final adyen.PaymentSessionFinished dropinResponse =
          await adyen.AdyenCheckout.session.startDropIn(
        dropInConfiguration: dropInConfiguration,
        checkout: sessionCheckout,
      ) as adyen.PaymentSessionFinished;
      
      if (dropinResponse.resultCode != adyen.ResultCode.authorised) {
      ...
```

**Comment by Robert-SD** [comment]
Hi @matmicro, 
You can handle the different outcomes of DropIn by using this example code. 
1) Start DropIn and wait for the PaymentResult: 
```dart
final PaymentResult paymentResult = await AdyenCheckout.session.startDropIn(
     dropInConfiguration: dropInConfiguration,
     checkout: sessionCheckout,
);
```

2) Check the different outcome of the PaymentResult. It can either be PaymentSessionFinished, PaymentCancelledByUser or a PaymentError:
```dart
    if (paymentResult case PaymentSessionFinished()) {
      print("Result code: ${paymentResult.resultCode.name}");
    } else if (paymentResult case PaymentCancelledByUser()) {
      print("Cancelled by user");
    } else if (paymentResult case PaymentError()) {
      print("${paymentResult.reason}");
    }
```
