### ISSUE TITLE
Use ThemeClass

### ISSUE THREAD

**Issue by matmicro** [Adyen/adyen-flutter#202]
I have an app which is declared this way:
```
class MyApp extends GetView<MainController> {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'MyApp',
      theme: ThemeClass.lightTheme,
      darkTheme: ThemeClass.darkTheme,
      themeMode: ThemeMode.light,
```

and themes are declared with:
```
  static ThemeData lightTheme = ThemeData(
      colorScheme: const ColorScheme.light(
...
```

What is the way to make Adyen widget using those current theme ?

Regards

**Comment by Robert-SD** [comment]
Hi @matmicro, 
you can find the documentation regarding customization [here](https://github.com/Adyen/adyen-flutter/tree/feature/improveAppearanceProvider?tab=readme-ov-file#ui-customization). 
Because we are using the native checkout libraries internally, customization needs to be done on the Android and iOS level. Styling through the Flutter theme is not supported. Please let me know if you need further assistance regarding applying a custom style.

**Comment by Robert-SD** [comment]
Great to hear that we succeeded with one step. You can find object names in our iOS [documentation](https://adyen.github.io/adyen-ios/5.8.0/documentation/adyen/customization/). 
In addition you can look into the [styling classes](https://github.com/Adyen/adyen-ios/tree/develop/Adyen/UI/Styles).

It's interesting that the style isn't applied for iOS. I've adjusted the example app and the style is applied correctly. Did you rebuild your app? I've opened an example for improving the style parsing. Could you try this branch: `feature/improveAppearanceProvider`? 

This is a screenshot from applying your style to the example app.
![Simulator Screenshot - iPhone 15 Pro - 2024-07-07 at 16 01 34](https://github.com/Adyen/adyen-flutter/assets/13377878/b8dc5b2c-0464-405b-a9c8-5546cbf3bd0d)

**Comment by Robert-SD** [comment]
@matmicro No worries, let's try to figure this out together. 
Could you check if createDropInStyle() is called at all? Have you rebuild the app instead of using hot reload? 
I assume you did, but just want to clarify. I've created a plain project and the styling worked as well again.

**Comment by Robert-SD** [comment]
Hi @matmicro, 
we simplified the styling by exposing the AdyenAppearance enum. This new approach will be available with the next release very soon. You can try it out yourself by using our main branch directly. Feel free to look into our updated [example](https://github.com/Adyen/adyen-flutter/blob/main/example/ios/Runner/AppDelegate.swift).
This adjustment should resolve the problem.

**Comment by Robert-SD** [comment]
Hi @matmicro, 
just a quick update. The new release is now available on [pub.dev](https://pub.dev/packages/adyen_checkout).
