### ISSUE TITLE
Live environment for GCC?

### ISSUE THREAD

**Issue by Yousuf-M-Hammad** [Adyen/adyen-flutter#224]
I've checked the currently available environments (Environment enum) and there is no Asia or GCC (Though there is apse and I couldn't find out what does it stand for nor there is docs for this accronym either), though I get it and I understand each account should get his own session link for live I've searched the example project with no refrence (except for the outsider calls for payment methods etc...).

So how to pass live environment in from the Environment enum for someone who is in UAE?

And how to pass our link (considering that I really don't understand why it should be passed? since I get the session from the back-end) to start accepting real payments, and thank you.

**Comment by Yousuf-M-Hammad** [comment]
@Robert-SD  Thank you for the APSE point! one thing left, is there any need to pass the checkout endpoint? and if yes where should I pass it in the library?

**Comment by Robert-SD** [comment]
@Yousuf-M-Hammad There is no need to pass the entire checkout endpoint. You only need to specify the environment in the DropInConfiguration. We find the endpoint based on the environment internally. 
```dart
 final DropInConfiguration dropInConfiguration = DropInConfiguration(
      environment: THE_ENVIRONMENT, // Environment.test or Environment.apse for live payments
      clientKey: THE_CLIENT_KEY,
      countryCode: THE_COUNTRY_CODE,
      ...
);
```

**Comment by Yousuf-M-Hammad** [comment]
Thanks for the clarification ❤️

**Comment by Robert-SD** [comment]
Your welcome! 💚🙂
I will close the issue, feel free to reopen it or create another one when you have more questions.
