### ISSUE TITLE
AdyenCardComponent and AdyenGooglePayComponent onPaymentResult - PaymentResult not being PaymentCancelledByUser when user cancels the 3ds pop up

### ISSUE THREAD

**Issue by drekyyy** [Adyen/adyen-flutter#226]
**Describe the bug**

AdyenCardComponent 3ds onPaymentResult - PaymentResult is PaymentError instead of PaymentCancelledByUser despite having a reason indicating payment being cancelled "Challenge has been cancelled.".

AdyenGooglePayComponent 3ds onPaymentResult - the returned result is PaymentError with reason = "com.adyen.checkout.adyen3ds2.Cancelled3DS2Exception: Challenge canceled."

**To Reproduce**
1. Go to AdyenCardComponent or AdyenGooglePayComponent view and use a test card with 3ds
2. Click on submit payment button
3. get PaymentResult from onPaymentResult method upon leaving the 3ds pop up

**Expected behavior**

Id expect PaymentResult being PaymentCancelledByUser if user cancelled/left the pop up, not a PaymentError with reason: "Challenge has been cancelled." for Card and "com.adyen.checkout.adyen3ds2.Cancelled3DS2Exception: Challenge canceled." for Google Pay

**Comment by Robert-SD** [comment]
Hi @drekyyy, 
Thank you for pointing out the behavior. I will check with the native mobile SDKs how a cancellation of 3DS is being handled. Will come back with the result.

**Comment by drekyyy** [comment]
Hey @Robert-SD 

Ive noticed the same issue with google pay 3ds - the returned result is PaymentError with reason = "com.adyen.checkout.adyen3ds2.Cancelled3DS2Exception: Challenge canceled."

I will slightly edit the description of this issue if you dont mind to include this google pay case aswell

**Comment by Robert-SD** [comment]
Hi @drekyyy, 
We will adjust the mapping in one of the next releases. Thanks again for spotting it (also for Google Pay)! 
I assume it's the case for all 3ds2 cancellations. Let's keep this issue open until the mapping adjustment is available.
