### ISSUE TITLE
Get last 4 card digits.

### ISSUE THREAD

**Issue by alextarrago** [Adyen/adyen-flutter#230]
Is there a way to retrieve the last 4 card digits for a CC payment method?

**Comment by Robert-SD** [comment]
Hi @alextarrago, 
Retrieve the last 4 card digits should be possible through the stored payment methods array from the /paymentMethods endpoint. Scheme objects contain a "lastFour" parameter providing the last 4 card digits. Would this be sufficient?

**Comment by Robert-SD** [comment]
Hello @alextarrago,
I would like to close the ticket and hope that using endpoint for retrieving the reaming for digits is sufficient. Please feel free to reopen the ticket in case of additional questions.
