### ISSUE TITLE
override content string on iOS

### ISSUE THREAD

**Issue by aboyo** [Adyen/adyen-flutter#245]
Hi, 
I want to change the title of the submit button. I referred to this [doc](https://github.com/Adyen/adyen-android/blob/develop/docs/UI_CUSTOMIZATION.md#overriding-string-resources) for Android. it works fine

howaver, in the iOS, I have followed this [guide](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=iOS&integration=Components&version=5.9.0#localization), and add Localizable.string, but it is not working.

How can I do the in iOS?

**Comment by aboyo** [comment]
> Hi @aboyo, Could you please share your integration and the flow? Do you use e.g. Drop-In with sessions? This would help further pinpointing the cause.
> 
> This [guide](https://adyen.github.io/adyen-ios/5.10.0/documentation/adyen/localization) provides the steps for adding custom localization. Adding the Localizable.strings is correct. You can find the key for the string you want to translate [here](https://github.com/Adyen/adyen-ios/blob/develop/Adyen/Assets/Generated/LocalizationKey.swift).
> 
> Custom strings are currently only supported if shopperLocale in the DropInConfiguration is null. Otherwise the default values are used.

it works if I do not set `shopperLoacle`.

**Comment by Robert-SD** [comment]
Thanks @aboyo for your reply! I'm happy that it works. 💚
