### ISSUE TITLE
ios build swift compiler errors

### ISSUE THREAD

**Issue by Shahin-Sefidgaran** [Adyen/adyen-flutter#246]
Hi adyen team
when I try to build the latest version of adyen_checkout flutter package for iOS I receive Swift compiler Errors
I am on xcode 14.2

`/Users/appleworld/Workspace/adyen-flutter/ios/Classes/components/instant/InstantSessionComponent.swift:39:13 Implicit use of 'self' in closure; use 'self.' to make capture semantics explicit`

 please tell me what I need to do to get a successful build on iOS

**Comment by Robert-SD** [comment]
Hi @Shahin-Sefidgaran, 
Thanks for raising the question. Would it be possible to try out the example app and does the error appear there as well?
Your Xcode version (14.2) is also older and currently not suitable to submit apps to the App Store. The minimum [requirement](https://developer.apple.com/ios/submit/) is Xcode 15. 
Would it be possible to update to Xcode 15?
