### ISSUE TITLE
CVC/CVV not disappearing

### ISSUE THREAD

**Issue by kaczmarzk** [Adyen/adyen-flutter#295]
**Describe the bug**

There are credit cards that do not require a CVC code. (our case UATP)
However, the card component requires CVC despite its use.

**To Reproduce**
Try to use some non CVC cards from link below.
https://docs.adyen.com/development-resources/testing/test-card-numbers/

**Expected behavior**
On web components, the CVC field disappears.

**Screenshots**
 
<img width="471" alt="Screenshot 2024-10-25 at 11 50 20" src="https://github.com/user-attachments/assets/1e5dd835-ac50-47c1-855d-7e8b930e0b99">
<img width="666" alt="image" src="https://github.com/user-attachments/assets/5e72a0b9-1e57-44d0-b317-bee840a9bea0">

**Comment by Robert-SD** [comment]
Hi @kaczmarzk , 

Thanks for reaching out and your comprehensive problem description. 
Unfortunately, the test card is indeed not recognized by the test bin lookup triggering the disappearing field. Apologies for this inconvenience. 

The behavior of a disappearing CVC/CVV field should work. You can test this by using a Bancontact (BCMC) card like “6703 4444 4444 4449”. Please keep in mind that you have to use BE as countryCode and it needs to be a supported card type.

**Comment by kaczmarzk** [comment]
So I understand that on production these cards will work properly and the CVC field will disappear?

**Comment by camil-adyen** [comment]
Hi @kaczmarzk, that is correct. Our LIVE BIN table will indicate if a specific BIN and/or card brand requires the CVC/CVV input field. If not, the UI will update and the field will be hidden. 

I'll close this issue for now. Feel free to reopen if you encounter any other issues.
