### ISSUE TITLE
PlatformException when call method channel

### ISSUE THREAD

**Issue by lipecosta00** [Adyen/adyen-flutter#305]
**Describe the bug**
Getting platform exception after call AdyenCheckout.instance.getReturnUrl()

`PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.getReturnUrl"., null, null)`

**To Reproduce**
1. Install using: `flutter pub add adyen_checkout`
2. Add `AdyenCheckout.instance.getReturnUrl()` to a FutureBuilder() widget and print the `snapshot.error` to see the error.

**Expected behavior**
Expected an String with return url.

**Screenshots**
![image](https://github.com/user-attachments/assets/63e82d9a-dbb8-4202-8d4f-1a0050a4bb0e)

**Smartphone (please complete the following information):**
 - Device: Pixel3a (emulator)
 - OS: api 34

**Additional context**
I'm using Flutter 3.19.0 and Dart 3.3.0.
Here is a snippet: https://gist.github.com/costaaaaaa/c1631f705509089bc945fc083b563522

**Comment by mumenahmedbright** [comment]
Same issue

**Comment by lipecosta00** [comment]
Found what happening: https://github.com/Adyen/adyen-flutter/issues/292 solved my problem.
Just use FlutterFragmentActivity on `android/MainActivity.kt`

**Comment by mumenahmedbright** [comment]
It worked! thank you.
Eventho I don't get what's the difference.

**Comment by lipecosta00** [comment]
With a little search I founded this:
**FlutterActivity**: Your app will be closed.
**FlutterFragmentActivity** : Your app will be move to background.
