### ISSUE TITLE
Card button gets partially hidden when there are errors in the form

### ISSUE THREAD

**Issue by lazarohcm** [Adyen/adyen-flutter#309]
**Describe the bug**
The Card button on `AdyenCardComponent` gets partially hidden when trying to submit it without filling out any details

**To Reproduce**
1. Go to the card form that uses `AdyenCardComponent`
2. Click on the button without filling out any of the details 
3. See the action button gets partially hidden

**Expected behavior**
The button should be fully visible

**Screenshots**
![IMG_6638](https://github.com/user-attachments/assets/7dce1c5a-98b2-44c8-99e1-3a8a88801109)

**Smartphone :**
 - Device: iPhone 11
 - OS: 17.2.1

**Comment by Robert-SD** [comment]
Hello @lazarohcm, 
thanks for opening the issue. I would like to reproduce the behavior. Could you share the SDK version you are using as well? 

We are using PlatformViews to render the native card component view. Whenever the height of the native view changes, the widget should adjust its sizes as well. I will double check that by also adding a bottom sheet containing the card component to the example app.
