### ISSUE TITLE
Sepa doesn't show in tokenization dropin but shows in authorization

### ISSUE THREAD

**Issue by mumenahmedbright** [Adyen/adyen-flutter#311]
My issue that whenever I try to authorize an amount from the user I can do it using sepa normally. But when I'm trying to tokenize I can't see it in flutter. the only difference between both requests is that in authorization we send the amount but in tokenization we send 0 as an amount. What is the issue here?

**To Reproduce**
Use this session data for example it has no Sepa,
"Ab02b4c0!BQABAgBKWsH2Z+SI5mMTd17BFJZ02pZtlQE1+aXBGSMBvLKnyCpTWU7TAPliaq7iJTrxBcyJJqVyfP8uKnJMcm35iA+yZT63QlssojUUMF8g4SJPxT7arqZtmJjo7yvgTgTWeJtkRM6wVpq19FxEb9wIND0fdrI75eIUvWUfZdMmMcPjR650/BKdk4syW8jTr+AkCD2rrtV154o4htIOWUISDwutmMiUnn7Em6LjJCld2kVmMyunyVqssoaujjrsBeXBktnnSwoodfCVz/ydLiMW+mSuLbLSmAbp7CFWg8UGEd0JdI4ypbq7+knXSuOOG3Z8LxMxGGxfUEJYogoZDv+DLKeVsnXkMNYkossJ7xivdNla+BOIjeo3gxT2T/DbtLErLkgj9Cu6hjUjEY4JuNv669sKIYYkeD/g94XL8sNLypQqwkV2PZmsEjdKMYUIu+lztkTuKFeelxJQfw2VkevyX/vKzxJESSefKKNtqFdwJ7BBKbyg/x67jtKZhd+8d/ckw0VXnLVaRNY/m7m/5Y21o2iUXMx7L7ppC6/FDorZjtkJCfUTbc3/Cuj4ztpJ4P4NrVX6V9rF/mzB0e1zZbZXS2Cweov35TXHsahX4Pb/LEK3LUgNlHUDNeWjstPKPMC4461CuEtQw7XjcsSvH3bWlGAsxq48InNfrxHFgH1FXCbEAgy8ok4eRzyqKgQM4nwASnsia2V5IjoiQUYwQUFBMTAzQ0E1MzdFQUVEODdDMjRERDUzOTA5QjgwQTc4QTkyM0UzODIzRDY4REFDQzk0QjlGRjgzMDVEQyJ9kDY3qXg9VFv363mDn3x0slo055MIwXxAQAo3GZkHZpsr1p41lOQLsOJRj86+8XMjaVmT4rUXJ9RgSCSIKMCPFPXc6TnRlVMolhMxs+MIFqQDMB7yBw3E3JCUng+3jBpyI6ghT44Vs+dRF7sQrf91UaxzUL1j+exKQC76WCaP9lDO0V56QWyOsDUZzkMr8CnzeWiswRi2fgJrbaWjvRcTJFjUcyAvek33UeaaCdvHx38oXT5EBbPyRlrd1ije1IzI/F5yoD55Gd4xG+cxPqAwUgt/2LWMZ/416CXJJf2QdM7GJJGhHIgeEIvdaLkiQIQeeXPu6+71egMnVQ44ZHXYq8vnacvzGU+UWqUCfjx8SH3eOE1IzNHNGmvjhYwUR0MlDxucr1IfeBPcT5Awf57Co4p3UxUHbdqlveoT85kYTAZikMKSO94HnolwsgDWDL+D6fFudykfQZ97Q0QP29T+MYBHAqNgPawcIu8sP00S/5B6JfR7NX7eACOeHUREChGQ6cdXkMHCGRUitDGThJS1DyGPmQVZp1UWZlSkXqBKE20CW+FkvBNE7/kE2CcmBCxtZ4FPOOEl1aGEl8kbslmzRarmnhXkEcMoGbMkxilB/CuBGnK8MBBaUG8vOAv6jUtN1XtHh3FDZNnkG5RkyOFVDsC55xgBdXk5bRdIMGOHswr71CxacBdBSWRnXEdqyYtp7jcDDl2to6S7GVA7sVf8VjMmnbi66UUPdn6Vyu25yEFQADeQJ2/0Mvs78ovT1Ct88QNBiXVqrnR9vZ9No1v5jxKtr8KCzO9HFJLHddRjldOkE1xUHXNufKtQ0XEdCYIZywBHH6GgYGUHtTBgyYJJhi0="

**Comment by Robert-SD** [comment]
Hi @mumenahmedbright,
Thanks for reaching out. Because we have to exchange payment payment relevant data (PSP etc.) to trace the issue, I would suggest to opening a ticket. I would like to avoid exposing data publicly here. 
Therefore, would it be possible to reach out to the support team via [Customer Area](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) or via email: [support@adyen.com](mailto:support@adyen.com)?

**Comment by Robert-SD** [comment]
Hi @mumenahmedbright, 
we would like to close the issue. Feel free to reopen it or reach out in case you have additional questions.
